### ISSUE TITLE
center nav links on mobile/small display

### ISSUE THREAD

**Issue by MayaGans** [dcossyleon/blogdown_desiree#16]
Hi! I freaking LOVE your underline animation under the text so I cough stole it... (with credit 😊 !)
I noticed on smaller screen mobile it renders funky

<img width="594" alt="Screen Shot 2020-08-13 at 8 38 36 PM" src="https://user-images.githubusercontent.com/6053906/90211439-893c6380-dda5-11ea-8fd1-796db2dedf47.png">

So I added which fixes it I think?

```
li.nav-item {
  text-align: center !important;
}
```

<img width="518" alt="Screen Shot 2020-08-13 at 8 39 26 PM" src="https://user-images.githubusercontent.com/6053906/90211424-804b9200-dda5-11ea-888d-9551c4a07fce.png">

Just wanted to give you a heads up and thank you for the code and constant UI inspo!!! XO

**Comment by dcossyleon** [comment]
Super delayed -- but nearly 2 years later, I am finally dusting off this website!! thank you for this fix, @MayaGans !
